using System;
using System.Diagnostics;
using Ectcs;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace EctcsTest
{
  [TestClass]
  public class SampleTest
  {
    private static readonly string list = @"<% linkHelper = (link) -> %>
    <li><a href=""<%- link.url %>""><%- link.name %></a></li>
<% end %>
<% if @links?.Length : %>
    <ul>
        <% for link in @links : %>
            <%- linkHelper link %>
        <% end %>
    </ul>
<% else : %>
    <p>List is empty</p>
<% end %>
";

    private static readonly string page = 
@"<% extend 'layout' %>
<div id=""<%- @id %>"">
  <h1><%- @upperHelper(@title) %></h1>
  <% include 'list' %>
</div>
<% block 'footer-info' : %>
  <div class=""right"">page: main</div>
<% end %>";

    private static readonly string footer = @"<div id=""footer"">
    <div class=""left"">Generated by ECT</div>
    <% content 'footer-info' %>
</div>";

    private static readonly string layout = @"<!DOCTYPE html>
<html>
    <head>
        <title><%- @title %></title>
    </head>
    <body>
        <% content %>
        <% include 'footer' %>
    </body>
</html>";

    [TestMethod]
    public void TestIf()
    {
      Test("TRUE", "<% if @test %>TRUE<% end %>", new { test = true});
      Test("TRUE", "<% if @test %>TRUE<% else %>FALSE<% end %>", new { test = true });
      Test("FALSE", "<% if @test %>TRUE<% else %>FALSE<% end %>", new { test = false });
    }

    [TestMethod]
    public void TestAccessor()
    {
      var o = new
      {
        a = new { test = true},
        b = (object)null
      };
      Test("True", "<%- @a.test %>", o);
      Test("True",  "<%- @a?.test %>", o);
      //Test("", "<%- @b?.test %>", o);
    }


    private void Test(string expected, string template, object self, EctOptions options = null)
    {
      options = options ?? new EctOptions();
      var ect = new Ect();
      var context = new EctRuntimeContext(ect, self);

      var lexer = new EctLexer("<void>", template, 0, template.Length, options);
      var parser = new EctCompiler(lexer);
      var lambda = parser.Compile();

      lambda(context, self);
      var result = context.Rendered;
      Debug.WriteLine("TEMPLATE =====>\n {0}\n\n RENDERED ====>\n{1}\n\n", template, result);
      Assert.AreEqual(expected, result);
    }

    [TestMethod]
    public void TestCompileNow()
    {
      var memory = new EctTemplateOnMemory();
      memory["/page"] = page;
      memory["/list"] = list;
      memory["/footer"] = footer;
      memory["/layout"] = layout;
      Func<string, string> helper = (s) => s.ToUpper();
      var self = new
      {
        title = "Hello, world!",
        id = "main",
        links = new object[]
        {
            new { ame = "Google", url = "http://google.com/" },
            new { name = "Facebook", url = "http://facebook.com/" },
            new { name = "Twitter", url = "http://twitter.com/" }
        },
        upperHelper = helper
      };

      var ect = new Ect(new EctOptions { OnMemory = memory });
      Debug.WriteLine(ect.Render("page", self));
    }
  }
}
